    <!-- REVOLUTION SLIDER -->
    <div class="pull-top-80px">

        <div id="rev_slider_13_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="salma-3" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
            <!-- START REVOLUTION SLIDER 5.4.8.1 fullwidth mode -->
            <div id="rev_slider_13_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8.1">
                <ul>
                    <!-- SLIDE  -->
                    <li data-index="rs-15" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                        <!-- MAIN IMAGE -->
                        <img src="assets/rslider/assets/e38a2-slider_3.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                        <!-- LAYERS -->

                        <!-- LAYER NR. 1 -->
                        <div class="tp-caption   tp-resizeme" id="slide-15-layer-1" data-x="['left','left','left','center']" data-hoffset="['30','36','27','1']" data-y="['top','top','top','top']" data-voffset="['256','255','262','169']" data-fontsize="['40','40','40','35']" data-lineheight="['70','70','70','38']" data-fontweight="['300','300','300','600']" data-color="['rgb(68,148,181)','rgb(68,148,181)','rgb(68,148,181)','rgb(56,15,143)']" data-width="['588','588','588','382']" data-height="['141','141','141','none']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1030,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; min-width: 588px; max-width: 588px; max-width: 141px; max-width: 141px; white-space: normal; font-size: 40px; line-height: 70px; font-weight: 300; color: #4494b5; letter-spacing: 0px;font-family:Josefin Sans;">Email marketing strategy and tips for successful campaigns
                        </div>

                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption   tp-resizeme" id="slide-15-layer-2" data-x="['left','left','left','center']" data-hoffset="['30','36','28','0']" data-y="['middle','middle','middle','middle']" data-voffset="['21','-6','-9','0']" data-width="['502','502','502','381']" data-height="['82','82','82','none']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":500,"speed":1020,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; min-width: 502px; max-width: 502px; max-width: 82px; max-width: 82px; white-space: normal; font-size: 16px; line-height: 32px; font-weight: 400; color: #666666; letter-spacing: 0px;font-family:Poppins;">With Salma’s flexible email marketing templates and intuitive designer, it's easy to send emails that really click.
                        </div>

                        <!-- LAYER NR. 3 -->
                        <div class="tp-caption rev-btn " id="slide-15-layer-3" data-x="['left','left','left','center']" data-hoffset="['30','33','23','-2']" data-y="['top','top','top','top']" data-voffset="['524','528','544','453']" data-width="167" data-height="50" data-whitespace="normal" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":960,"speed":1020,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(56,15,143);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[15,15,15,15]" data-paddingright="[35,35,35,35]" data-paddingbottom="[15,15,15,15]" data-paddingleft="[35,35,35,35]" style="z-index: 7; min-width: 167px; max-width: 167px; max-width: 50px; max-width: 50px; white-space: normal; font-size: 14px; line-height: 17px; font-weight: 500; color: rgba(255,255,255,1); letter-spacing: 0px;font-family:Poppins;text-transform:uppercase;background-color:rgba(68,148,181,0.74);border-color:rgba(0,0,0,1);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Read More </div>

                        <!-- LAYER NR. 4 -->
                        <div class="tp-caption rev-btn " id="slide-15-layer-4" data-x="['left','left','left','left']" data-hoffset="['220','213','202','634']" data-y="['top','top','top','top']" data-voffset="['525','529','543','514']" data-width="164" data-height="48" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":1600,"speed":920,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"0","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(252,91,83);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[15,15,15,15]" data-paddingright="[35,35,35,35]" data-paddingbottom="[15,15,15,15]" data-paddingleft="[35,35,35,35]" style="z-index: 8; min-width: 164px; max-width: 164px; max-width: 48px; max-width: 48px; white-space: nowrap; font-size: 14px; line-height: 17px; font-weight: 500; color: rgba(255,255,255,1); letter-spacing: 0px;font-family:Poppins;text-transform:uppercase;background-color:rgba(255,180,29,0.75);border-color:rgba(0,0,0,1);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Contact Us </div>
                    </li>
                </ul>
                
                <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
            </div>
        </div>

    </div>
    <!-- END REVOLUTION SLIDER -->